/**
 * CSV Map Viewer – 11‑layer interactive viewer
 * ==============================================
 * Loads a packed 64‑bit per‑pixel CSV file (generated by the map creator) and
 * displays individual map layers (SeaLand, Height, Country, Province,
 * Temperature, AreaType, Forest, Soil, ResID, ResNum, Infra) using colour‑
 * coded buttons. The currently active layer’s button stays visually pressed.
 *
 * Bit layout (MSB → LSB):
 *   [SeaLand:1][Height:8][Country:8][Province:8][Temperature:6]
 *   [AreaType:6][Forest:6][Soil:6][ResID:6][ResNum:6][Infra:3]
 *
 * Each layer is colour‑mapped independently:
 *   - SeaLand      : Black (sea) / White (land)
 *   - Height       : Grayscale (0 = black, 255 = white)
 *   - Country      : Red scale
 *   - Province     : Green scale
 *   - Temperature  : Red scale (0 = black, 63 = bright red)
 *   - AreaType     : Green scale
 *   - Forest       : Green scale
 *   - Soil         : Green scale
 *   - ResID        : Green scale
 *   - ResNum       : Grayscale
 *   - Infra        : Blue scale
 */

#include <windows.h>
#include <cstdint>
#include <vector>
#include <string>
#include <fstream>
#include <sstream>
#include <algorithm>

// ============================================================================
// Enums & Constants
// ============================================================================

enum MapMode
{
    MODE_SEALAND,
    MODE_HEIGHT,
    MODE_COUNTRY,
    MODE_PROVINCE,
    MODE_TEMPERATURE,
    MODE_AREATYPE,
    MODE_FOREST,
    MODE_SOIL,
    MODE_RESID,
    MODE_RESNUM,
    MODE_INFRA,
    MODE_COUNT,
};

// Labels displayed on the layer‑selector buttons (two rows).
static const wchar_t *ModeNames[MODE_COUNT] = {
    L"SeaLand",
    L"Height",
    L"Country",
    L"Province",
    L"Temperature",
    L"AreaType",
    L"Forest",
    L"Soil",
    L"ResID",
    L"ResNum",
    L"Infra",
};

// ============================================================================
// Application State – holds everything the window needs to render the map.
// ============================================================================
struct AppState
{
    int width = 0;
    int height = 0;

    // Original 64‑bit values read from the CSV (one per pixel).
    std::vector<uint64_t> map_values;

    // RGBA pixels ready for StretchDIBits (32 bits per pixel, ARGB layout).
    std::vector<uint32_t> pixels;

    // Describes the DIB format (width, height, bit count, …).
    BITMAPINFO bitmap_info = {};

    // Currently selected map layer (invalid initial value forces first SetMode to work).
    MapMode mode = MODE_COUNT;

    // Handles to the layer‑selector buttons (one per mode).
    HWND buttons[MODE_COUNT] = {};

    // True after a CSV has been successfully loaded.
    bool loaded = false;
};

// Single global instance – because it's a small tool, a global is acceptable.
static AppState g_state;

// ============================================================================
// CSV Loading
// ============================================================================

static bool LoadCsvFile(const std::wstring &path, AppState &state)
{
    // Convert the wide path to a narrow string (ASCII is safe for file paths).
    std::string narrowPath(path.begin(), path.end());
    std::ifstream file(narrowPath);
    if (!file.is_open())
        return false;

    int max_x = -1;
    int max_y = -1;
    std::vector<std::tuple<int, int, uint64_t>> temp;
    std::string line;

    while (std::getline(file, line))
    {
        if (line.empty())
            continue;

        std::stringstream ss(line);
        int x = 0, y = 0;
        std::string token;
        std::string value_text;

        // Expect first token: x coordinate.
        if (!std::getline(ss, token, ','))
            continue;
        if (token == "x" || token == "X") // skip header line
            continue;
        try
        {
            x = std::stoi(token);
        }
        catch (...)
        {
            continue;
        }

        // Second token: y coordinate.
        if (!std::getline(ss, token, ','))
            continue;
        if (token == "y" || token == "Y")
            continue;
        try
        {
            y = std::stoi(token);
        }
        catch (...)
        {
            continue;
        }

        // Third token: hex value.
        if (!std::getline(ss, value_text, ','))
            continue;

        uint64_t value = 0;
        try
        {
            value = std::stoull(value_text, nullptr, 0);
        }
        catch (...)
        {
            continue;
        }

        temp.emplace_back(x, y, value);
        max_x = std::max(max_x, x);
        max_y = std::max(max_y, y);
    }

    if (max_x < 0 || max_y < 0)
        return false; // no valid data found

    // Create a dense 2D array with dimensions based on the largest coordinates.
    state.width = max_x + 1;
    state.height = max_y + 1;
    state.map_values.assign((size_t)state.width * (size_t)state.height, 0);

    // Fill in the values at the specified coordinates.
    for (auto &entry : temp)
    {
        int x = std::get<0>(entry);
        int y = std::get<1>(entry);
        uint64_t value = std::get<2>(entry);
        state.map_values[(size_t)y * state.width + x] = value;
    }

    // Prepare the pixel buffer (same size, initially empty).
    state.pixels.assign((size_t)state.width * (size_t)state.height, 0);

    // Set up the BITMAPINFO that describes a 32‑bit top‑down DIB.
    // biHeight negative → first row is the top of the image.
    state.bitmap_info.bmiHeader.biSize = sizeof(state.bitmap_info.bmiHeader);
    state.bitmap_info.bmiHeader.biWidth = state.width;
    state.bitmap_info.bmiHeader.biHeight = -state.height;
    state.bitmap_info.bmiHeader.biPlanes = 1;
    state.bitmap_info.bmiHeader.biBitCount = 32;
    state.bitmap_info.bmiHeader.biCompression = BI_RGB;
    state.bitmap_info.bmiHeader.biSizeImage = state.width * state.height * 4;

    state.loaded = true;
    return true;
}

// ============================================================================
// Data Extraction & Colouring
// ============================================================================

static uint64_t ExtractFieldValue(uint64_t packed, MapMode mode)
{
    switch (mode)
    {
    case MODE_SEALAND:
        return (packed >> 63) & 0x1ULL;
    case MODE_HEIGHT:
        return (packed >> 55) & 0xFFULL;
    case MODE_COUNTRY:
        return (packed >> 47) & 0xFFULL;
    case MODE_PROVINCE:
        return (packed >> 39) & 0xFFULL;
    case MODE_TEMPERATURE:
        return (packed >> 33) & 0x3FULL;
    case MODE_AREATYPE:
        return (packed >> 27) & 0x3FULL;
    case MODE_FOREST:
        return (packed >> 21) & 0x3FULL;
    case MODE_SOIL:
        return (packed >> 15) & 0x3FULL;
    case MODE_RESID:
        return (packed >> 9) & 0x3FULL;
    case MODE_RESNUM:
        return (packed >> 3) & 0x3FULL;
    case MODE_INFRA:
        return (packed >> 0) & 0x7ULL;
    default:
        return 0;
    }
}

static uint32_t ValueToColor(uint64_t value, MapMode mode)
{
    uint8_t r = 0, g = 0, b = 0;

    switch (mode)
    {
    case MODE_SEALAND:
        // Black (sea) / White (land)
        if (value == 0)
        {
            r = 0;
            g = 0;
            b = 0;
        }
        else
        {
            r = 255;
            g = 255;
            b = 255;
        }
        break;

    case MODE_HEIGHT:
        // Grayscale: 0 = black, 255 = white
        r = g = b = (uint8_t)value;
        break;

    case MODE_COUNTRY:
        r = (uint8_t)value;
        break;

    case MODE_PROVINCE:
        g = (uint8_t)value;
        break;

    case MODE_TEMPERATURE:
        // Red scale: 0 → black, 63 → bright red
        r = (uint8_t)((value * 255) / 63);
        break;

    case MODE_AREATYPE:
    case MODE_FOREST:
    case MODE_SOIL:
    case MODE_RESID:
        // Green scale, 0‑63 → 0‑255
        g = (uint8_t)((value * 255) / 63);
        break;

    case MODE_RESNUM:
        // Grayscale, 0‑63 → 0‑255
        r = g = b = (uint8_t)((value * 255) / 63);
        break;

    case MODE_INFRA:
        // Red scale, 0‑7 → 0‑255
        r = (uint8_t)((value * 255) / 7);
        break;

    default:
        break;
    }

    // Assemble the final colour: A = 0xFF, R = r, G = g, B = b.
    return 0xFF000000 | (r << 16) | (g << 8) | b;
}

// ============================================================================
// Pixel Buffer Update
// ============================================================================

static void UpdatePixels(AppState &state)
{
    if (!state.loaded)
        return;

    size_t count = (size_t)state.width * (size_t)state.height;
    for (size_t i = 0; i < count; ++i)
    {
        uint64_t field = ExtractFieldValue(state.map_values[i], state.mode);
        state.pixels[i] = ValueToColor(field, state.mode);
    }
}

// ============================================================================
// Mode Switching (with Button Management)
// ============================================================================

static void SetMode(AppState &state, MapMode mode)
{
    if (state.mode != mode)
    {
        // Unpress the old button (if it exists).
        if (state.buttons[state.mode] != nullptr)
            SendMessageW(state.buttons[state.mode], BM_SETSTATE, FALSE, 0);

        // Press the new button.
        if (state.buttons[mode] != nullptr)
            SendMessageW(state.buttons[mode], BM_SETSTATE, TRUE, 0);

        state.mode = mode;
        UpdatePixels(state);
    }
}

// ============================================================================
// Window Procedure – Handles All OS Messages
// ============================================================================

static LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{
    switch (uMsg)
    {
    case WM_CREATE:
    {
        // First row – 6 buttons (SeaLand … Temperature)
        for (int i = 0; i < 6; ++i)
        {
            g_state.buttons[i] = CreateWindowW(
                L"BUTTON", ModeNames[i],
                WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_PUSHBUTTON,
                10 + i * 90, 10, 84, 28,
                hwnd,
                reinterpret_cast<HMENU>(1000 + i),
                nullptr, nullptr);
        }
        // Second row – 5 buttons (AreaType … Infra)
        for (int i = 6; i < MODE_COUNT; ++i)
        {
            g_state.buttons[i] = CreateWindowW(
                L"BUTTON", ModeNames[i],
                WS_TABSTOP | WS_VISIBLE | WS_CHILD | BS_PUSHBUTTON,
                10 + (i - 6) * 90, 42, 84, 28,
                hwnd,
                reinterpret_cast<HMENU>(1000 + i),
                nullptr, nullptr);
        }

        // Initialise to the SeaLand layer (this call also presses the button).
        SetMode(g_state, MODE_SEALAND);
        return 0;
    }

    case WM_SIZE:
    {
        // Reposition the two rows when the window is resized.
        for (int i = 0; i < 6; ++i)
            MoveWindow(g_state.buttons[i], 10 + i * 90, 10, 84, 28, TRUE);
        for (int i = 6; i < MODE_COUNT; ++i)
            MoveWindow(g_state.buttons[i], 10 + (i - 6) * 90, 42, 84, 28, TRUE);

        // Force a complete repaint.
        InvalidateRect(hwnd, nullptr, TRUE);
        return 0;
    }

    case WM_COMMAND:
    {
        int id = LOWORD(wParam);
        // If a layer button was clicked (IDs 1000 … 1000 + MODE_COUNT‑1).
        if (id >= 1000 && id < 1000 + MODE_COUNT)
        {
            SetMode(g_state, (MapMode)(id - 1000));
            InvalidateRect(hwnd, nullptr, TRUE);
        }
        return 0;
    }

    case WM_PAINT:
    {
        PAINTSTRUCT ps;
        HDC hdc = BeginPaint(hwnd, &ps);
        RECT client_rect;
        GetClientRect(hwnd, &client_rect);

        if (g_state.loaded && !g_state.pixels.empty())
        {
            // Leave space for two rows of buttons at the top.
            int button_area = 96;
            int draw_width = client_rect.right - client_rect.left;
            int draw_height = client_rect.bottom - client_rect.top - button_area - 10;
            RECT draw_rect = {0, button_area + 10, draw_width, button_area + 10 + draw_height};

            // Blit the pixel buffer to the window, scaling if necessary.
            StretchDIBits(hdc,
                          draw_rect.left, draw_rect.top,
                          draw_rect.right - draw_rect.left,
                          draw_rect.bottom - draw_rect.top,
                          0, 0,
                          g_state.width, g_state.height,
                          g_state.pixels.data(),
                          &g_state.bitmap_info,
                          DIB_RGB_COLORS,
                          SRCCOPY);
        }
        else
        {
            // If no map is loaded, show an error message centered in the window.
            std::wstring text = L"Failed to load CSV or no data available.";
            DrawTextW(hdc, text.c_str(), (int)text.size(), &client_rect,
                      DT_CENTER | DT_VCENTER | DT_SINGLELINE);
        }

        EndPaint(hwnd, &ps);
        return 0;
    }

    case WM_DESTROY:
        // Quit the application when the window is closed.
        PostQuitMessage(0);
        return 0;
    }

    // For all other messages, use the default handling.
    return DefWindowProc(hwnd, uMsg, wParam, lParam);
}

// ============================================================================
// Application Entry Point
// ============================================================================

int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                    PWSTR pCmdLine, int nCmdShow)
{
    // Default CSV path (relative to the executable).
    std::wstring csv_path = L"GameFiles\\Map\\BaseMap.csv";

    // Check for a command‑line argument that overrides the default path.
    int argc;
    LPWSTR *argv = CommandLineToArgvW(GetCommandLineW(), &argc);
    if (argv)
    {
        if (argc >= 2)
            csv_path = argv[1];
        LocalFree(argv);
    }

    // Load the CSV data. If it fails, show an error message and quit.
    if (!LoadCsvFile(csv_path, g_state))
    {
        MessageBoxW(nullptr,
                    L"Failed to load CSV file. Place output.csv in the program "
                    L"folder or pass the path as the first argument.",
                    L"CSV Load Error", MB_OK | MB_ICONERROR);
        return 1;
    }

    // Immediately compute the display pixels so the window shows the map
    // right from the start (fixes the "blank on first open" bug).
    UpdatePixels(g_state);

    // Register the window class.
    WNDCLASSW wc = {};
    wc.lpfnWndProc = WindowProc;
    wc.hInstance = hInstance;
    wc.lpszClassName = L"CsvMapViewerWindowClass";
    wc.hCursor = LoadCursor(nullptr, IDC_ARROW);
    wc.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);

    RegisterClassW(&wc);

    // Size the window to at least 640×480, but try to make it 4× the map
    // dimensions so individual pixels are visible.
    int window_width = std::max(640, g_state.width * 4);
    int window_height = std::max(480, g_state.height * 4 + 64 + 48); // extra 48 for second button row

    HWND hwnd = CreateWindowW(
        wc.lpszClassName, L"CSV Map Viewer",
        WS_OVERLAPPEDWINDOW,
        CW_USEDEFAULT, CW_USEDEFAULT,
        window_width, window_height,
        nullptr, nullptr, hInstance, nullptr);

    if (!hwnd)
        return 1;

    ShowWindow(hwnd, nCmdShow);
    UpdateWindow(hwnd);

    // Standard Windows message loop.
    MSG msg;
    while (GetMessageW(&msg, nullptr, 0, 0))
    {
        TranslateMessage(&msg);
        DispatchMessageW(&msg);
    }

    return (int)msg.wParam;
}

/*
===========================================================================
BUILD INSTRUCTIONS (MinGW-w64 / Git Bash)
===========================================================================
Open Git Bash in the project directory and run:

   g++ -std=c++20 -O2 -static -municode -o map_viewer.exe map_viewer.cpp -lgdi32 -luser32

   Explanation of flags:
     -std=c++20  : Use the C++20 standard.
     -O2         : Optimise for speed and size.
     -static     : Link everything into a single .exe – no external DLLs needed.
     -municode   : Use the Unicode entry point (wWinMain). REQUIRED.
     -lgdi32     : Link GDI32 library (StretchDIBits, painting).
     -luser32    : Link User32 library (windows, buttons, messages).

===========================================================================
USAGE
===========================================================================
AUTO MODE (double‑click):
   The viewer looks for "GameFiles\\Map\\BaseMap.csv" (relative to the exe)
   or, if a command‑line argument is given, the path passed as the first
   argument.
   A window opens showing the SeaLand layer by default.  Click the buttons
   to switch layers (SeaLand, Height, Country, Province, Temperature,
   AreaType, Forest, Soil, ResID, ResNum, Infra). The active button stays
   pressed.

   If the CSV is missing or invalid, an error message box appears.

MANUAL OVERRIDE:
   map_viewer.exe "C:\path\to\other.csv"

To change the default CSV path, edit the "csv_path" variable at the top of
wWinMain() in this source file.
===========================================================================
*/